server:
  port: 8088

spring:
  application:
    name: mhpractice
  profiles:
    active: local
  thread:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  logging:
    level:
      root: INFO

  datasource:
    url: jdbc:postgresql://localhost:5435/mhpractice
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
      
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls: 
            enabled: false
app:
  jwt:
    secret: secretKey
    encryption-key: encryptionKey
    expiration-ms: ms
    refresh-expiration-ms: ms

  cookie: 
    secure: true

  scheduler:
    cleanup-cron: "0 0 0 * * ?"  # Daily at midnight
